### ISSUE TITLE
pudb flashing on every step

### ISSUE THREAD

**Issue by horida** [isaacbernat/docker-pudb#3]
Thanks for the nice write-up. Once thing I noticed is that on every step, e.g. `n`, the pudb screen flashes (reloads completely). That is something I do not experience when debugging code running "locally" on the host.
Any idea why? Do you have the same issue?

**Comment by isaacbernat** [comment]
Does this happen to you with `pudb-example` from this repo or trying docker and pudb on some other code? I just ran the instructions from the readme without any incidents.

**Comment by horida** [comment]
With a python3.6 docker container

**Comment by isaacbernat** [comment]
I am sorry, I couldn't reproduce the bug. I'll close the issue for the time being.
